services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sb
      POSTGRES_PASSWORD: sb
      POSTGRES_DB: shirel
    ports: ["5432:5432"]           # exposes DB to your WSL host (handy for psql)
    volumes: [pgdata:/var/lib/postgresql/data]  # keeps data between restarts

  api:
    build: ./api                   # uses api/Dockerfile
    env_file: ./api/.env.dev       # injects env vars into the api container
    ports: ["8000:8000"]           # localhost:8000 -> FastAPI
    depends_on: [db]               # ensure db starts first

volumes:
  pgdata:
